### ISSUE TITLE
Have a way to disable MissingCultureFormat when there is a string

### ISSUE THREAD

**Issue by EchterAgo** [JohanLarsson/Gu.Localization#11]
It would be very nice to have a way to disable the MissingCultureFormat when the resource manager returns a string as otherwise I always have to maintain 2 resource dictionaries for English as it is my Neutral language. Also in case the user has a system with a translation that I do not provide I do not want to have ~ around all my English strings.

**Comment by EchterAgo** [comment]
Having this only makes sense during development and debugging anyway.

**Comment by EchterAgo** [comment]
Please see the proposed fix in #12

**Comment by EchterAgo** [comment]
Now that I think about it more, it is still not complete because the StaticExtension still uses the other error handling mechanism. I have worked around it in my code though.

**Comment by JohanLarsson** [comment]
Thanks, for the issue & PR!
