### ISSUE TITLE
API for using ErrorHandling in the static extension

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/Gu.Localization#14]
I'm thinking:
1) Defne an attached property:
  - Of type `ErrorHandling?`
  - DefaultValue = null
  - With inheritance 
  - Bindable = false (to simplify things so we don't have to track and update)

Supporting binding & updates is not a huge issue but don't think it solves a problem that will be needed often, can be added later also.

2) Define a property on the staticextension `public ErrorHandling? ErrorHandling { get; set; }`

This way we can define errorhandling per extension or on a control for example a grid. Using nullable we can have a fallback chain local > attached prop > global
For global I think we don't want throw.

What do you think @EchterAgo?

**Comment by EchterAgo** [comment]
This sounds very good.

**Comment by JohanLarsson** [comment]
Ok, I'll try to write a PR with it today so you can review.

**Comment by JohanLarsson** [comment]
@EchterAgo I did not write it as a PR, pushed [this](https://github.com/JohanLarsson/Gu.Localization/commit/b9125d21e11263c7b263e0ad179174415e064604) to master.

What do you think about the names?

**Comment by EchterAgo** [comment]
Sorry, I will check it soon. Just got up.

**Comment by JohanLarsson** [comment]
Rewrote some other stuff in the lib, tried to clean up some messy parts. Think I'll release a new major version.

**Comment by JohanLarsson** [comment]
I published new packages, bumped major, don't remember if I broke public API in some place so just to be safe.

**Comment by EchterAgo** [comment]
I tested it, it does pretty much what I wanted. One nice thing would be able to set the StaticExtension error handling globally.

**Comment by JohanLarsson** [comment]
You mean a static property on the StaticExtension?
When is this usedful when you can do 
```
<MainWindow l:ErrorHandling.Mode="ReturnErrorInfoPreserveNeutral" ...>...</MainWindow>
```

Adding the static property will introduce some complexity in the fallback chain and then some if we want to be responsive to changes. Not saying it is a bad idea, just want to make sure there is a use case.

**Comment by EchterAgo** [comment]
Oh, OK, didn't realize I could set it on the main window. Thank you! 👍

**Comment by JohanLarsson** [comment]
I'll update the docs with it now when it is released.

**Comment by JohanLarsson** [comment]
Added some text to the docs: https://github.com/JohanLarsson/Gu.Localization#11-errorhandling
I don't know English well so I don't expect the docs to be awesome.

**Comment by EchterAgo** [comment]
I think your English is fine, and the documentation is good to get quickly and easyly started with Gu.Localization. The reason why I didn't realize you can set the error handling on the main window is that I'm quite new to WPF programming, only started it around 1 month ago.

**Comment by JohanLarsson** [comment]
Oh, the mechanism enabling it is dependency property inheritance. It is not obvious at all. Sometimes it is a nice way to solve problems.
For example you can do:
```xaml
<Grid TextElement.FontSize="24">
    ...
</Grid>
```
Then fontsize will be set to 24 for child controls if not overriden.You can read about the precedence rules [here](https://msdn.microsoft.com/en-us/library/ms743230(v=vs.110).aspx)

Another way would be to set the property in the default style for `TextBox`

**Comment by JohanLarsson** [comment]
I released an updated package with more verbose exception messages suggesting fixes.
