### ISSUE TITLE
Language Selector AutogenerateLanguages fails to get neutral language

### ISSUE THREAD

**Issue by 537mfb** [JohanLarsson/Gu.Localization#19]
when using:

`<l:LanguageSelector AutogenerateLanguages="True" />`

and having two languages (1 specific (resources.pt.resx) and a neutral (resources.resx)) only the specific one is shown.

The standard dictates that a line similar to:

`[assembly: NeutralResourcesLanguage("en-US", UltimateResourceFallbackLocation.MainAssembly)]`

should be added to Assembly.cs but the language selector ignores it and ignores the neutral languages that serves as a fallback when a specific resource for the culture is missing

**Comment by JohanLarsson** [comment]
Thanks for reporting! Do you want to have a go at fixing it?

**Comment by JohanLarsson** [comment]
@537mfb If you have time you can review the diff. 
I'm releasing an updated nuget now, if you find errors we release another one.

**Comment by 537mfb** [comment]
Hi @JohanLarsson - sorry for the late reply - i am away for hollydays right now
i'll see about testing this today or tomorrow and get back to you

**Comment by JohanLarsson** [comment]
Nice, thanks!

**Comment by 537mfb** [comment]
Hi @JohanLarsson 

Just took a few moments to test this - and it's working - it gets the neutral language from the assembly and uses the base resx for it when that language is selected - perfect, no more duplicate resx files for neutral language

Improvement Notes:
When the assembly doesn't set a neutral (no  [assembly: NeutralResourcesLanguage("en-US", UltimateResourceFallbackLocation.MainAssembly)] like line in assembly.cs or it's commented out), .NET assumes en-US as default - your library should assume en as default for this cases aswell - at the moment if the line is missing, your selector just shows the languages with satellite dlls as before

Notice i said your library should assume en and not en-US - when AutogenerateLanguages is set to true en-US doesn't show a flag while en does
