### ISSUE TITLE
Cultures does not contain all available cultures

### ISSUE THREAD

**Issue by EchterAgo** [JohanLarsson/Gu.Localization#20]
The check seems to be to check all the culture sub directories and look for *.resources.dll. This check fails if the assemblies have been merged using Costura.Fody or similar tools. There should be a better way to determine all available cultures or a way to override the check. I'm not quite sure how to proceed here correctly.

**Comment by EchterAgo** [comment]
See also https://github.com/tgjones/gemini/pull/243

**Comment by JohanLarsson** [comment]
Thanks for reporting!
Everything around this is a huge hack. I could not figure out a clean way.
One way we could ~fix it is by making the cultures property an `ObservableCollection<CultureInfo>`
Then overriding would be possible. Not elegant but perhaps useful?

**Comment by EchterAgo** [comment]
Yes, that would be very useful. Maybe providing some callback mechanism to modifying language discovery. What I'm doing as a workaround right now is very unorthodox:

```c#
            var allCulturesField = typeof(Translator).GetField("allCultures", BindingFlags.Static | BindingFlags.NonPublic);
            var allCultures = (SortedSet<CultureInfo>)allCulturesField.GetValue(null);
            foreach (var culture in CultureInfo.GetCultures(CultureTypes.AllCultures))
                allCultures.Add(culture);
```

Another solution I've been trying is to get all the resource managers and query their supported cultures, but that fails when not all assemblies of a project are loaded yet.

**Comment by JohanLarsson** [comment]
Yeah, also I think doing it can leak some memory loading everything. I did another hack around that loading into a temp manager. Maybe there is a nice way to use the `ResourceManager` class that I don't know of.

About this issue, do you feel like writing a PR?
I'm a bit busy so it will probably be until the weekend before I can look at it.

**Comment by EchterAgo** [comment]
I will write a PR, to turn Cultures into an `ObservableCollection`. I will also think some more about any ways to do this nicer.

**Comment by JohanLarsson** [comment]
We could perhaps create an `ObservableSet<T>`? 
Also maybe we need to handle existing translations if langauges changes, hopefully it is simple as they are all singletons in a static list.
Wrote it like that to not have memory leaks from subscribing to static events.

**Comment by JohanLarsson** [comment]
@EchterAgo does ^ look ok?
