### ISSUE TITLE
Can't get NuGet package

### ISSUE THREAD

**Issue by nestquik** [JohanLarsson/Gu.Localization#26]
When I'm trying to get latest (6.2.1) **Gu.Localization** and **Gu.Localization.Wpf** packages NuGet downloader throws exception:

> Failed to add reference. The package 'SourceLink' tried to add a framework reference to 'FSharp.Core' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by JohanLarsson** [comment]
Thanks for reporting, stupid mistake by me, sorry about that. Released new packages now.
